# Generated by Django 4.1.2 on 2021-07-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=50)),
                ('check_in', models.CharField(max_length=30)),
                ('check_out', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
