# Generated by Django 4.1.2 on 2021-07-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
